export type { GamePrivateState, HostGameRecord } from './private-state.js';
export {
  loadOrCreateSecretKey,
  privateStateFor,
  rememberHostGame,
  hostRecordFor,
  bytesToHex,
  hexToBytes,
} from './private-state.js';
export {
  buildWitnesses,
  ledgerToRoomState,
  encodeInviteLink,
  decodeInviteLink,
  privateStateIdFor,
  computeTargetHash,
  generateTargetNumber,
  generateRoomCode,
  codeToRoomId,
  roomIdToCode,
  type GameState,
  type GamePhase,
} from './game-api.js';
export {
  NETWORK_CONFIG,
  applyNetworkId,
  getAvailableWallets,
  getFirstCompatibleWallet,
  connectMidnightWallet,
  connectLaceWallet,
  buildBrowserProviders,
  type GameProviders,
  type GameCircuit,
  type WalletInfo,
} from './providers.js';
export {
  compiledGuessingGame,
  deployHub,
  connectToHub,
  readRoomState,
  subscribeRoomState,
  callFaucet,
  callCreateRoom,
  callJoinRoom,
  callGuess,
  callDeclareWinner,
  callGiveUp,
  callCancelRoom,
  callClaimRefund,
  type CreateRoomParams,
  type DeployedHub,
  // Backwards compatibility
  connectToGame,
  readGameState,
  subscribeGameState,
  callJoinGame,
  callCancelGame,
  type DeployedGame,
} from './game-client.js';
